2020-11-03 17:46:15 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.bilibili.com/v/popular/rank/all?rt=V%2FymTlOu4ow%2Fy4xxNWPUZy01ay2PUjMaY3hLY9QfLSY%3D> (referer: None)
Traceback (most recent call last):
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 62, in _evaluate_iterable
    for r in iterable:
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 62, in _evaluate_iterable
    for r in iterable:
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 340, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 62, in _evaluate_iterable
    for r in iterable:
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 62, in _evaluate_iterable
    for r in iterable:
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 62, in _evaluate_iterable
    for r in iterable:
  File "E:\PyDev\bilipy\bilipy\spiders\bilibili.py", line 64, in parse
    self.openfile('../txts/' + item['rank_type']+'Titles.txt', titleTxt)
  File "E:\PyDev\bilipy\bilipy\spiders\bilibili.py", line 38, in openfile
    with io.open(path, 'a+', newline='', encoding='gb18030') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../txts/全站榜Titles.txt'
2020-11-03 17:46:15 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.bilibili.com/v/popular/rank/food?rt=V%2FymTlOu4ow%2Fy4xxNWPUZy01ay2PUjMa1WEgyKgdQ2A%3D> (referer: None)
Traceback (most recent call last):
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 62, in _evaluate_iterable
    for r in iterable:
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 62, in _evaluate_iterable
    for r in iterable:
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 340, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 62, in _evaluate_iterable
    for r in iterable:
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 62, in _evaluate_iterable
    for r in iterable:
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 62, in _evaluate_iterable
    for r in iterable:
  File "E:\PyDev\bilipy\bilipy\spiders\bilibili.py", line 64, in parse
    self.openfile('../txts/' + item['rank_type']+'Titles.txt', titleTxt)
  File "E:\PyDev\bilipy\bilipy\spiders\bilibili.py", line 38, in openfile
    with io.open(path, 'a+', newline='', encoding='gb18030') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../txts/美食榜Titles.txt'
2020-11-03 17:47:09 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.bilibili.com/v/popular/rank/digital?rt=V%2FymTlOu4ow%2Fy4xxNWPUZy01ay2PUjMa0rAWy34XcD8%3D> (referer: None)
Traceback (most recent call last):
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 62, in _evaluate_iterable
    for r in iterable:
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 62, in _evaluate_iterable
    for r in iterable:
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 340, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 62, in _evaluate_iterable
    for r in iterable:
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 62, in _evaluate_iterable
    for r in iterable:
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 62, in _evaluate_iterable
    for r in iterable:
  File "E:\PyDev\bilipy\bilipy\spiders\bilibili.py", line 64, in parse
    self.openfile('../txts/' + item['rank_type']+'Titles.txt', titleTxt)
  File "E:\PyDev\bilipy\bilipy\spiders\bilibili.py", line 38, in openfile
    with io.open(path, 'a+', newline='', encoding='gb18030') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../txts/数码榜Titles.txt'
2020-11-03 17:47:09 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.bilibili.com/v/popular/rank/food?rt=V%2FymTlOu4ow%2Fy4xxNWPUZy01ay2PUjMaENfPId7Lw8k%3D> (referer: None)
Traceback (most recent call last):
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 62, in _evaluate_iterable
    for r in iterable:
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 62, in _evaluate_iterable
    for r in iterable:
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 340, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 62, in _evaluate_iterable
    for r in iterable:
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 62, in _evaluate_iterable
    for r in iterable:
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 62, in _evaluate_iterable
    for r in iterable:
  File "E:\PyDev\bilipy\bilipy\spiders\bilibili.py", line 64, in parse
    self.openfile('../txts/' + item['rank_type']+'Titles.txt', titleTxt)
  File "E:\PyDev\bilipy\bilipy\spiders\bilibili.py", line 38, in openfile
    with io.open(path, 'a+', newline='', encoding='gb18030') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../txts/美食榜Titles.txt'
2020-11-03 17:47:09 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.bilibili.com/v/popular/rank/origin?rt=V%2FymTlOu4ow%2Fy4xxNWPUZy01ay2PUjMaTs2FhqzOPb0%3D> (referer: None)
Traceback (most recent call last):
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 62, in _evaluate_iterable
    for r in iterable:
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 62, in _evaluate_iterable
    for r in iterable:
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 340, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 62, in _evaluate_iterable
    for r in iterable:
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 62, in _evaluate_iterable
    for r in iterable:
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 62, in _evaluate_iterable
    for r in iterable:
  File "E:\PyDev\bilipy\bilipy\spiders\bilibili.py", line 64, in parse
    self.openfile('../txts/' + item['rank_type']+'Titles.txt', titleTxt)
  File "E:\PyDev\bilipy\bilipy\spiders\bilibili.py", line 38, in openfile
    with io.open(path, 'a+', newline='', encoding='gb18030') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../txts/原创榜Titles.txt'
2020-11-03 17:47:10 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.bilibili.com/v/popular/rank/all?rt=V%2FymTlOu4ow%2Fy4xxNWPUZy01ay2PUjMaKtzxGjSgeKw%3D> (referer: None)
Traceback (most recent call last):
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 62, in _evaluate_iterable
    for r in iterable:
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 62, in _evaluate_iterable
    for r in iterable:
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 340, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 62, in _evaluate_iterable
    for r in iterable:
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 62, in _evaluate_iterable
    for r in iterable:
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 62, in _evaluate_iterable
    for r in iterable:
  File "E:\PyDev\bilipy\bilipy\spiders\bilibili.py", line 64, in parse
    self.openfile('../txts/' + item['rank_type']+'Titles.txt', titleTxt)
  File "E:\PyDev\bilipy\bilipy\spiders\bilibili.py", line 38, in openfile
    with io.open(path, 'a+', newline='', encoding='gb18030') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../txts/全站榜Titles.txt'
2020-11-03 17:47:10 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.bilibili.com/v/popular/rank/rookie?rt=V%2FymTlOu4ow%2Fy4xxNWPUZy01ay2PUjMaT7ohxXWLCP8%3D> (referer: None)
Traceback (most recent call last):
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 62, in _evaluate_iterable
    for r in iterable:
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 62, in _evaluate_iterable
    for r in iterable:
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 340, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 62, in _evaluate_iterable
    for r in iterable:
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 62, in _evaluate_iterable
    for r in iterable:
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 62, in _evaluate_iterable
    for r in iterable:
  File "E:\PyDev\bilipy\bilipy\spiders\bilibili.py", line 64, in parse
    self.openfile('../txts/' + item['rank_type']+'Titles.txt', titleTxt)
  File "E:\PyDev\bilipy\bilipy\spiders\bilibili.py", line 38, in openfile
    with io.open(path, 'a+', newline='', encoding='gb18030') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../txts/新人榜Titles.txt'
2020-11-03 17:47:10 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.bilibili.com/v/popular/rank/life?rt=V%2FymTlOu4ow%2Fy4xxNWPUZy01ay2PUjMa0rAWy34XcD8%3D> (referer: None)
Traceback (most recent call last):
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\utils\defer.py", line 120, in iter_errback
    yield next(it)
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\utils\python.py", line 353, in __next__
    return next(self.data)
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 62, in _evaluate_iterable
    for r in iterable:
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 62, in _evaluate_iterable
    for r in iterable:
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 340, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 62, in _evaluate_iterable
    for r in iterable:
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 62, in _evaluate_iterable
    for r in iterable:
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "e:\users\xcl\anaconda3\lib\site-packages\scrapy\core\spidermw.py", line 62, in _evaluate_iterable
    for r in iterable:
  File "E:\PyDev\bilipy\bilipy\spiders\bilibili.py", line 64, in parse
    self.openfile('../txts/' + item['rank_type']+'Titles.txt', titleTxt)
  File "E:\PyDev\bilipy\bilipy\spiders\bilibili.py", line 38, in openfile
    with io.open(path, 'a+', newline='', encoding='gb18030') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../txts/生活榜Titles.txt'
